solid = "../icons/solid/"
brands = "../icons/brands/"

const icons = {
    "email" : solid + "envelope.svg",
    "domain" : solid + "building.svg",
    "criminal" : solid + "angry.svg",
    "malware" : solid + "bug.svg",
    "vector" : solid + "bus.svg",
    "lightDrug" : solid + "cannabis.svg",
    "heavyDrug" : solid + "capsules.svg",
    "IOC" : solid + "car-crash.svg",
    "admin" : solid + "crown.svg",
    "child" : solid + "child.svg",
    "market" : solid + "city.svg",
    "cloud" : solid + "cloud.svg",
    "forum" : solid + "comments.svg",
    "creditCard" : solid + "credit-card.svg",
    "arms" : solid + "crosshairs.svg",
    "dumps" : solid + "datasolid.svg",
    "pdf" : solid + "file-pdf.svg",
    "audio" : solid + "file-audio.svg",
    "image" : solid + "file-image.svg",
    "ppt" : solid + "file-powerpoint.svg",
    "video" : solid + "file-video.svg",
    "docx" : solid + "file-word.svg",
    "fingerprint" : solid + "fingerprint.svg",
    "key" : solid + "key.svg",
    "position" : solid + "map-marked-alt.svg",
    "user" : solid + "user-alt.svg",
    "bitcoin" : brands + "bitcoin.svg",
    "discord" : brands + "discord.svg",
    "facebook" : brands + "facebook.svg",
    "keybase" : brands + "keybase.svg",
    "linkedin" : brands + "linkedin.svg",
    "monero" : brands + "monero.svg",
    "paypal" : brands + "paypal.svg",
    "reddit" : brands + "reddit.svg",
    "skype" : brands + "skype.svg",
    "snapchat" : brands + "snapchat-square.svg",
    "stackOverflow" : brands + "stack-overflow.svg",
    "telegram" : brands + "telegram.svg",
    "tumblr" : brands + "tumblr-square.svg",
    "twitter" : brands + "twitter.svg",
    "vk" : brands + "vk.svg",
    "whatsapp" : brands + "whatsapp.svg",
    "yahoo" : brands + "yahoo.svg",
    "youtube" : brands + "youtube.svg",
}