const solid = "../icons/solid/"
const brands = "../icons/brands/"

const email = solid + "envelope.svg";
const domain = solid + "building.svg";
const criminal = solid + "angry.svg";
const malware = solid + "bug.svg";
const vector = solid + "bus.svg";
const lightDrug = solid + "cannabis.svg";
const heavyDrug = solid + "capsules.svg";
const IOC = solid + "car-crash.svg";
const admin = solid + "crown.svg";
const child = solid + "child.svg";
const market = solid + "city.svg";
const cloud = solid + "cloud.svg";
const forum = solid + "comments.svg";
const creditCard = solid + "credit-card.svg";
const arms = solid + "crosshairs.svg";
const dumps = solid + "datasolid.svg";
const pdf = solid + "file-pdf.svg";
const audio = solid + "file-audio.svg";
const image = solid + "file-image.svg";
const ppt = solid + "file-powerpoint.svg";
const video = solid + "file-video.svg";
const docx = solid + "file-word.svg";
const fingerprint = solid + "fingerprint.svg";
const key = solid + "key.svg";
const location = solid + "map-marked-alt.svg";
const user = solid + "user-alt.svg";

const bitcoin = brands + "bitcoin.svg";
const discord = brands + "discord.svg";
const facebook = brands + "facebook.svg";
const keybase = brands + "keybase.svg";
const linkedin = brands + "linkedin.svg";
const monero = brands + "monero.svg";
const paypal = brands + "paypal.svg";
const reddit = brands + "reddit.svg";
const skype = brands + "skype.svg";
const snapchat = brands + "snapchat-square.svg";
const stackOverflow = brands + "stack-overflow.svg";
const telegram = brands + "telegram.svg";
const tumblr = brands + "tumblr-square.svg";
const twitter = brands + "twitter.svg";
const vk = brands + "vk.svg";
const whatsapp = brands + "whatsapp.svg";
const yahoo = brands + "yahoo.svg";
const youtube = brands + "youtube.svg";

